#!/bin/sh
ssh ubuntu@172-31-28-102 <<EOF
    cd ~/nodejs-jenkins-aws-test
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v16.13.2
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF